[package]
name = "ldd"
version.workspace = true
rust-version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand.workspace = true
rustc-hash = "1.1"
ahash = "0.8"
static_assertions = "1.1"