name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: on

jobs:
  test:
    name: Test
    strategy:
      fail-fast: false
      matrix:      
        os: [ubuntu-20.04, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Setup sccache
      uses: mozilla-actions/sccache-action@v0.0.3

    - name: Checkout repository
    - uses: actions/checkout@v3

    - name: Run tests
      run: cargo test --verbose       
      env:
        RUSTC_WRAPPER: sccache
